/**
* jQuery.UI.iPad plugin
* Copyright (c) 2010 Stephen von Takach
* licensed under MIT.
* Date: 27/8/2010
*
* Project Home: 
* http://code.google.com/p/jquery-ui-for-ipad-and-iphone/
*/
(function(e){e.extend(e.support,{touch:"ontouchend" in document});e.fn.addTouch=function(){if(e.support.touch){this.each(function(o,p){p.addEventListener("touchstart",a,false);p.addEventListener("touchmove",a,false);p.addEventListener("touchend",a,false);p.addEventListener("touchcancel",a,false)})}return this};var h=null;var m=false;var j=null;function c(){m=false}var i=false;var d=null;var g=null;var b=false;function f(){if(i){window.clearTimeout(g);i=false;d=null}}function n(o){if(i){return}i=true;d=(o.changedTouches)[0];g=window.setTimeout("doRightClick();",800)}function l(){i=false;var p=d,o=document.createEvent("MouseEvent");o.initMouseEvent("mouseup",true,true,window,1,p.screenX,p.screenY,p.clientX,p.clientY,false,false,false,false,0,null);p.target.dispatchEvent(o);o=document.createEvent("MouseEvent");o.initMouseEvent("mousedown",true,true,window,1,p.screenX,p.screenY,p.clientX,p.clientY,false,false,false,false,2,null);p.target.dispatchEvent(o);o=document.createEvent("MouseEvent");o.initMouseEvent("contextmenu",true,true,window,1,p.screenX+50,p.screenY+5,p.clientX+50,p.clientY+5,false,false,false,false,2,null);p.target.dispatchEvent(o);b=true;d=null}function k(q){var r=q.changedTouches,s=r[0],o="mouseover",p=document.createEvent("MouseEvent");p.initMouseEvent(o,true,true,window,1,s.screenX,s.screenY,s.clientX,s.clientY,false,false,false,false,0,null);s.target.dispatchEvent(p);o="mousedown";p=document.createEvent("MouseEvent");p.initMouseEvent(o,true,true,window,1,s.screenX,s.screenY,s.clientX,s.clientY,false,false,false,false,0,null);s.target.dispatchEvent(p);if(!m){h=s.target;m=true;j=window.setTimeout(c,600);n(q)}else{window.clearTimeout(j);if(s.target==h){h=null;m=false;o="click";p=document.createEvent("MouseEvent");p.initMouseEvent(o,true,true,window,1,s.screenX,s.screenY,s.clientX,s.clientY,false,false,false,false,0,null);s.target.dispatchEvent(p);o="dblclick";p=document.createEvent("MouseEvent");p.initMouseEvent(o,true,true,window,1,s.screenX,s.screenY,s.clientX,s.clientY,false,false,false,false,0,null);s.target.dispatchEvent(p)}else{h=s.target;m=true;j=window.setTimeout(c,600);n(q)}}}function a(r){var p="",o=0;if(r.touches.length>1){return}switch(r.type){case"touchstart":if(e(r.changedTouches[0].target).is("select")){return}k(r);r.preventDefault();return false;break;case"touchmove":f();p="mousemove";r.preventDefault();break;case"touchend":if(b){b=false;r.preventDefault();return false}f();p="mouseup";break;default:return}var s=r.changedTouches,t=s[0],q=document.createEvent("MouseEvent");q.initMouseEvent(p,true,true,window,1,t.screenX,t.screenY,t.clientX,t.clientY,false,false,false,false,o,null);t.target.dispatchEvent(q);if(p=="mouseup"&&m&&t.target==h){q=document.createEvent("MouseEvent");q.initMouseEvent("click",true,true,window,1,t.screenX,t.screenY,t.clientX,t.clientY,false,false,false,false,o,null);t.target.dispatchEvent(q)}}})(jQuery);